directives:
  child-src:
    - "'self'"
    - 'blob:'
  worker-src:
    - "'self'"
    - 'blob:'
  connect-src:
    - "'self'"
    - 'blob:'
    - 'https://tile.openstreetmap.org/'
    - 'https://protomaps.github.io/'
    - 'http://localhost:9205/'
  default-src:
    - "'none'"
  font-src:
    - "'self'"
  frame-ancestors:
    - "'self'"
  frame-src:
    - "'self'"
    - 'blob:'
    - 'https://embed.diagrams.net/'
    - 'https://docs.opencloud.eu'
  img-src:
    - "'self'"
    - 'data:'
    - 'blob:'
    - 'https://tile.openstreetmap.org/'
  manifest-src:
    - "'self'"
  media-src:
    - "'self'"
  object-src:
    - "'self'"
    - 'blob:'
  script-src:
    - "'self'"
    - "'unsafe-inline'"
    - 'https://www.gstatic.com/'
  style-src:
    - "'self'"
    - "'unsafe-inline'"
